[package]
name = "pam_blox"
version = "0.1.0"
authors = ["Mihail Milev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pam_blox"
crate-type = ["dylib"]

[dependencies]
regex = "1.4.3"
